// src/components/Parts/ContactButton/ContactButton.tsx
import React from "react";

import {CopyIcon} from "@/IndexImporter";
import "./ContactButton.scss";

const ContactButton: React.FC<{
    copyid: string;
    type: string;
    title: string;
    content: string;
    link?: string;
}> = ({
    copyid, type, title, content, link,
}) => {
    const copy = (content: string, copyid: string) => {
        const copyAlert = document.querySelector(`#${copyid}`);
        navigator.clipboard.writeText(content);
        if (copyAlert) {
            copyAlert.classList.toggle("displayed");
            setTimeout(() => {
                copyAlert.classList.toggle("displayed");
            }, 2000);
        }
    };

    return (
        <div className="one-contact-container">
            <img
                alt="logo représentant le launcher cité"
                className="contact-icon"
                src={`/src/assets/images/contactLogo/${copyid}.png`}
            />
            {type === "link"
                ? (
                    <a
                        className="contact-title contact-title-link"
                        href={link}
                        rel="noreferrer"
                        target="_blank"
                    >
                        {title}
                    </a>
                )
                : null}
            {type === "copy"
                ? (
                    <button
                        className="contact-title"
                        type="button"
                        onClick={() => copy(content, copyid)}
                    >
                        {title}
                    </button>
                )
                : null}
            <CopyIcon handleCopy={() => copy(content, copyid)} />
            <span
                className="copy-confirm-alert"
                id={copyid}
            >
                Copié !
            </span>
        </div>
    );
};

export default ContactButton;

// src/views/Parts/ContactButton.vue
<script setup>
const copy = (content, copyid) => {
    const copyAlert = document.querySelector(`#${copyid}`);
    navigator.clipboard.writeText(content);
    copyAlert.classList.toggle("displayed");
    setTimeout(() => {
        copyAlert.classList.toggle("displayed");
    }, 2000);
};

defineProps({
    copyid: {
        type: String,
        required: true,
    },
    type: {
        type: String,
        required: true,
    },
    title: {
        type: String,
        required: true,
    },
    content: {
        type: String,
        required: true,
    },
    section: {
        type: String,
        required: false,
        default: "pro",
    },
});
    
</script>

<template>
    <div class="one-contact-box">
        <a v-if="type === 'link'" :href="copyid" target="_blank" class="contact-element">
            <span class="contact-title">{{ title }}</span>
            <span class="contact-content link">{{ content }}</span>
        </a>


        <button v-if="type === 'copy'" class="contact-element" @click="copy(content, copyid)">
            <span class="contact-title">
                <img v-if="section === 'games'" class="launcher-logo" :src="require(`../../images/laucherLogo/${copyid}.png`)" alt="logo représentant le launcher cité">
                {{ title }}
            </span>
            <span class="contact-content">{{ content }}</span>
            <div class="copy-icon">
                <svg
                    xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="{1.5}"
                    stroke="currentColor" className="copy-icon"
                >
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25zM6.75 12h.008v.008H6.75V12zm0 3h.008v.008H6.75V15zm0 3h.008v.008H6.75V18z" />
                </svg>
            </div>
        </button>
        <span :id="copyid" class="copy-confirm-alert">Copié !</span>
    </div>
</template>
